version: '3.8'
services:
  perkeep:
    build: .
    image: tullo/perkeep-amd64:0.1.0
    ports:
    - published: 3179
      target: 3179
    restart: unless-stopped
    volumes:
    - pk_config:/home/perkeep/.config/perkeep:rw
    - pk_storage:/storage:rw
volumes:
  pk_config: {}
  pk_storage: {}
